<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC5fhfau\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC5fhfau/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerC5fhfau.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerC5fhfau\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerC5fhfau\appProdProjectContainer([
    'container.build_hash' => 'C5fhfau',
    'container.build_id' => '52d7dc3f',
    'container.build_time' => 1593956871,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC5fhfau');
